name: 'Set up Canvas Build'
description: 'Set up canvas build environment.'
inputs:
  canvas-home:
    description: 'Directory of canvas.'
    required: false
    default: 'apps/canvas'
  arch:
    description: 'OS and Arch to build.'
    required: false
    default: 'ALL'
outputs:
  emsdk-path:
    description: 'Path of emsdk.'
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
